### ISSUE TITLE
Missing dependencies?

### ISSUE THREAD

**Issue by henn1nk** [tivac/crucible#74]
```
> crucible@0.0.1 start /Users/hendrik/work/crucible
> node build/serve.js


/Users/hendrik/work/crucible/node_modules/postcss-import/index.js:13
var resolvedPromise = new Promise(function(resolvePromise) {
                          ^
ReferenceError: Promise is not defined
    at Object.<anonymous> (/Users/hendrik/work/crucible/node_modules/postcss-import/index.js:13:27)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/hendrik/work/crucible/build/serve.js:58:9)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

**Comment by tivac** [comment]
We're developing this against `node@5.x` so you'll need to install a Promise shim.
